In [1]:
from IPython.display import Image
Image(url='http://datascience.uci.edu/wp-content/uploads/sites/2/2014/09/data_science_logo_with_image1.png')

## Preliminaries

1.  If you haven't do so already, download and **install the [Anaconda Scientific Python Distribution](https://store.continuum.io/cshop/anaconda/)**.  If it offers to make itself your default Python distribution, allow it.
1. Whether you've just installed Anaconda, or you have done so previously, you should now **update Anaconda** to the latest version of the distribution.  It changes a lot so do this today even if you did recently.
 1. Open a terminal or command prompt.
 1. Type ```conda update conda``` and press enter or return.  Confirm that you'd like it to make any changes that it offers.
 1. Type ```conda update anaconda``` and press enter or return.  Confirm that you'd like it to make any changes that it offers.
1. **Download the code repository**.  
 1. Go to [bit.ly/uci_predictive](http://bit.ly/uci_predictive) and click the "download zip" button on the right to download a zip file containing this entire repository.
 1. Unzip that file into a directory you know how to find; you'll need it several times throughout the day.  
1. **Start an ipython notebook server**.
 1. Open a terminal and type ```ipython notebook```.  Navigate to the directory where you unzipped this repository.
 1. Open "Test Notebook.ipynb".
 1. Click "Cell" at the top of the opened notebook, followed by "Run All" and ensure that 1) there are no errors and that 2) the output from the first cell is the same as that in the second.  If it doesn't match, raise your hand.
 1. If everything looks good, close the browser tab containing the test notebook but keep open the tab listing all the other notebooks.

### Schedule for Today

|Start Time | Session |
|-----------|---------|
|8:30am     | Check In|
|9:00am     | **The IPython Notebook and Pandas** |
|10:30am    | Coffee & Bagels|
|10:45am    | **Linear Regression and Predictive Modeling** |
|12:30pm    | Lunch|
|1:00pm     | **Out of Sample Prediction** |
|2:45pm     | Afternoon break|
|3:00pm     | **Logistic Regression** |

## Predictive Modeling with Python - _IPython Notebooks and Viewing Data in Python_
#### Author: Kevin Bache

## Outline
1. IPython and IPython Notebooks
1. Numpy
1. Pandas

## Python and IPython
* `python` is a programming language and also the name of the program that runs scripts written in that language.
* If you're running scripts from the command line you can use either `ipython` with something like `ipython my_script.py` or `python` with something like `python my_script.py`
* If you're using the command line interpreter interactively to load and explore data, try out a new package, etc. always use `ipython` over `python`.  This is because `ipython` has a bunch of features like tab completion, inline help, and easy access to shell commands which are just plain great (more on these in a bit).

## IPython Notebook
* IPython notebook is an interactive front-end to ipython which lets you combine snippets of python code with explanations, images, videos, whatever.  
* It's also really convenient for conveying experimental results.
* http://nbviewer.ipython.org

### <span style="color:red">IPython Notebook Exercise #1</span>
1. Start a terminal window and cd to the directory where you stored the course files
1. Start the IPython Notebook server with the command `ipython notebook`.  The IPython notebook server runs your python code behind the scenes and renders the output into the notebook
1. Create a new notebook by clicking New (top right) >> Python 2 Notebook

### Notebook Concepts
* **Cells** -- That grey box is called a cell.  An IPython notebook is nothing but a series of cells.  
* **Selecting** -- You can tell if you have a cell selected because it will have a thin, black box around it.
* **Running a Cell** -- Running a cell displays its output.  You can run a cell by pressing **`shift + enter`** while it's selected (or click the play button toward the top of the screen). 
* **Modes** -- There are two different ways of having a cell selected:
  * **Command Mode** -- Lets you delete a cell and change its type (more on this in a second).
  * **Edit Mode** -- Lets you change the contents of a cell.

### Aside: Keyboard Shortcuts That I Use A Lot
* (When describing keyboard shortcuts, `+` means 'press at the same time', `,` means 'press after'
* **`Enter`** -- Run this cell and make a new one after it
* **`Esc`** -- Stop editing this cell
* **`Option + Enter`** -- Run this cell and make a new cell after it (Note: this is OSX specific.  Check help >> keyboard shortcuts to find your operating system's version)
* **`Shift + Enter`** -- Run this cell and don't make a new one after it
* **`Up Arrow`** and **`Down Arrow`**  -- Navigate between cells (must be in command mode)
* **`Esc, m, Enter`** -- Convert the current cell to markdown and start editing it again
* **`Esc, y, Enter`** -- Convert the current cell to a code cell and start editing it again
* **`Esc, d, d`** -- Delete the current cell
* **`Esc, a`** -- Create a new cell above the current one
* **`Esc, b`** -- Create a new cell below the current one
* **`Command + /`** -- Toggle comments in Python code (OSX)
* **`Ctrl + /`** -- Toggle comments in Python code (Linux / Windows)

### <span style="color:red">IPython Notebook Exercise #2</span>
1. Click Help >> User Interface Tour and take the tour
1. Click Help >> Keyboard Shortcuts.  Mice are for suckers.

### More Notebook Concepts
* **Cell Types** -- There are 3 types of cells: python, markdown, and raw.
  * **Python Cells** -- Contain python code. Running a python cell displays its output. Press **`y`** in command mode convert any selected cell into a python cell. All cells start their lives as python cells.
  * **Markdown Cells** -- Contain formatted text, lists, links, etc. Press **`m`** in command mode to convert the selected cell into a markdown cell.
  * **Raw Cells** -- Useful for a few advanced corner cases.  We won't deal with these at all today.
  
### <span style="color:red">IPython Notebook Exercise #3</span>:
1. Partner up with someone next to you
  1. Create a code cell
    1. IPython notebooks offer tab completion.  Try typing: ```a<tab>``` 
    1. IPython notebooks offer inline help.  Try typing: ```?abs``` and then running the cell
  1. Create and render a markdown cell which contains 
    1. Bold text
    1. A nested numbered list
    1. A working link to UCI's website
    1. An image
    1. Some rendered LaTex. 
  1. **Hint**: The following websites might be useful:
    1. Check out this [Markdown Cheat Sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).  Markdown is a set of simple commands for formatting text to make it pretty.  It isn't specific to IPython Notebooks; it's used all over (for example, a lot of blogging platforms let you write your content in markdown because it's easy and HTML is a pain in the butt).
    1. Check out this [stackoverflow post](http://stackoverflow.com/questions/13208286/how-to-write-latex-in-ipython-notebook) about using LaTex in IPython Notebooks.

## Numpy
Numpy is the main package that you'll use for doing scientific computing in Python.  Numpy provides a multidimensional array datatype called `ndarray` which can do things like vector and matrix computations.

### Resources:
* [Official Numpy Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)
* [Numpy, R, Matlab Cheat Sheet](http://mathesaurus.sourceforge.net/matlab-python-xref.pdf)
* [Another Numpy, R, Matlab Cheat Sheet](http://sebastianraschka.com/Articles/2014_matrix_cheatsheet_table.html)

In [1]:
# you don't have to rename numpy to np but it's customary to do so
import numpy as np

# you can create a 1-d array with a list of numbers
a = np.array([1, 4, 6])
print 'a:'
print a
print 'a.shape:', a.shape
print 

# you can create a 2-d array with a list of lists of numbers
b = np.array([[6, 7], [3, 1], [4, 0]])
print 'b:'
print b
print 'b.shape:', b.shape
print


a:
[1 4 6]
a.shape: (3,)

b:
[[6 7]
 [3 1]
 [4 0]]
b.shape: (3, 2)



In [2]:
# you can create an array of ones
print 'np.ones(3, 4):'
print np.ones((3, 4))
print

# you can create an array of zeros
print 'np.zeros(2, 5):'
print np.zeros((2, 5))
print

# you can create an array which of a range of numbers and reshape it
print 'np.arange(6):'
print np.arange(6)
print 
print 'np.arange(6).reshape(2, 3):'
print np.arange(6).reshape(2, 3)
print

# you can take the transpose of a matrix with .transpose or .T
print 'b and b.T:'
print b
print 
print b.T
print 

np.ones(3, 4):
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

np.zeros(2, 5):
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

np.arange(6):
[0 1 2 3 4 5]

np.arange(6).reshape(2, 3):
[[0 1 2]
 [3 4 5]]

b and b.T:
[[6 7]
 [3 1]
 [4 0]]

[[6 3 4]
 [7 1 0]]



In [3]:
# you can iterate over rows
i = 0
for this_row in b:
    print 'row', i, ': ', this_row
    i += 1 
print 
    
# you can access sections of an array with slices
print 'first two rows of the first column of b:'
print b[:2, 0]
print

row 0 :  [6 7]
row 1 :  [3 1]
row 2 :  [4 0]

first two rows of the first column of b:
[6 3]



np.hstack([b, b]):
[[6 7 6 7]
 [3 1 3 1]
 [4 0 4 0]]

np.vstack([b, b]):
[[6 7]
 [3 1]
 [4 0]
 [6 7]
 [3 1]
 [4 0]]



In [5]:
# note that you get an error if you pass in print 'np.hstack(b, b):'
print np.hstack([b, b])
print


[[6 7 6 7]
 [3 1 3 1]
 [4 0 4 0]]



In [39]:
# you can perform matrix multiplication with np.dot()
a = np.array([1, 4, 6])
b = np.array([[6, 7], [3, 1], [4, 0]])
print (a)
print (b)
c = np.dot(a, b)
print ('c = np.dot(a, b):')
print (c)
print

# you can perform element-wise multiplication with * 
d = b * b
print ('d = b * b:')
print (d)
print


[1 4 6]
[[6 7]
 [3 1]
 [4 0]]
c = np.dot(a, b):
[42 11]
d = b * b:
[[36 49]
 [ 9  1]
 [16  0]]


<function print>

### Arrays and Matrices
In addition to arrays which can have any number of dimensions, Numpy also has a `matrix` data type which always has exactly 2.  **DO NOT USE `matrix`**.  

The original intention behind this data type was to make Numpy feel a bit more like Matlab, mainly by making the `*` operator perform matrix multiplication so you don't have to use `np.dot`.  But `matrix` isn't as well developed by the Numpy people as `array` is.  `matrix` is slower and using it will sometimes throw errors in other people's code because everyone expects you to use `array`.

In [7]:
# you can convert a 1-d array to a 2-d array with np.newaxis
print 'a:'
print a
print 'a.shape:', a.shape
print 
print 'a[np.newaxis] is a 2-d row vector:'
print a[np.newaxis]
print 'a[np.newaxis].shape:', a[np.newaxis].shape
print

print 'a[np.newaxis].T: is a 2-d column vector:'
print a[np.newaxis].T
print 'a[np.newaxis].T.shape:', a[np.newaxis].T.shape
print


a:
[1 4 6]
a.shape: (3,)

a[np.newaxis] is a 2-d row vector:
[[1 4 6]]
a[np.newaxis].shape: (1, 3)

a[np.newaxis].T: is a 2-d column vector:
[[1]
 [4]
 [6]]
a[np.newaxis].T.shape: (3, 1)



In [8]:
# numpy provides a ton of other functions for working with matrices
m = np.array([[1, 2],[3, 4]])
m_inverse = np.linalg.inv(m)
print 'inverse of [[1, 2],[3, 4]]:'
print m_inverse
print

print 'm.dot(m_inverse):'
print m.dot(m_inverse)

inverse of [[1, 2],[3, 4]]:
[[-2.   1. ]
 [ 1.5 -0.5]]

m.dot(m_inverse):
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [9]:
# and for doing all kinds of sciency type stuff.  like generating random numbers:
np.random.seed(5678)
n = np.random.randn(3, 4)
print 'a matrix with random entries drawn from a Normal(0, 1) distribution:'
print n

a matrix with random entries drawn from a Normal(0, 1) distribution:
[[-0.70978938 -0.01719118  0.31941137 -2.26533107]
 [-1.37745366  1.94998073 -0.56381007 -0.84373759]
 [ 0.22453858 -0.39137772  0.60550347 -0.68615034]]


### <span style="color:red">Numpy Exercise</span>
1. In the cell below, add a column of ones to the matrix `X_no_constant`.  This is a common task in linear regression and general linear modeling and something that you'll have to be able to do later today.  
1. Multiply your new matrix by the `betas` vector below to make a vector called `y`
1. You'll know you've got it when the cell prints '\*\*\*\*\*\* Tests passed! \*\*\*\*\*\*' at the bottom.

Specificically, given a matrix:

\begin{equation*}
\qquad
\mathbf{X_{NoConstant}} = 
\left( \begin{array}{ccc}
x_{1,1} & x_{1,2} & \dots & x_{1,D} \\
x_{2,1} & x_{2,2} & \dots & x_{2,D} \\
\vdots & \vdots & \ddots & \vdots \\
x_{i,1} & x_{i,2} & \dots & x_{i,D} \\
\vdots & \vdots & \ddots & \vdots \\
x_{N,1} & x_{N,2} & \dots & x_{N,D} \\
\end{array} \right)
\qquad
\end{equation*}

We want to convert it to:
\begin{equation*}
\qquad
\mathbf{X} = 
\left( \begin{array}{ccc}
1 & x_{1,1} & x_{1,2} & \dots & x_{1,D} \\
1 & x_{2,1} & x_{2,2} & \dots & x_{2,D} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{i,1} & x_{i,2} & \dots & x_{i,D} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{N,1} & x_{N,2} & \dots & x_{N,D} \\
\end{array} \right)
\qquad
\end{equation*}

So that if we have a vector of regression coefficients like this:

\begin{equation*}
\qquad
\beta = \left( \begin{array}{ccc}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_j \\
\vdots \\
\beta_D
\end{array} \right)
\end{equation*}

We can do this:

\begin{equation*}
\mathbf{y} \equiv \mathbf{X}^T \mathbf{\beta} 
\end{equation*}


In [54]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

print (betas)

X_no_constant = np.random.randn(n_data, n_dim)
print ('X_no_constant:')
print (X_no_constant)
print 

print (X_no_constant.shape)

# INSERT YOUR CODE HERE!

onesv=np.ones((10, 1))
print (onesv)

#[[ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]]

baseX=np.hstack([X_no_constant, onesv])

#Transpose matrix
baseX.T
print (baseX.T)

baseX.T.shape
betas.shape


#matrix multiplication
# you can perform matrix multiplication with np.dot()
y = np.dot(betas.reshape(1,6),baseX.T)

# Tests:
y_expected = np.array([-0.41518357, -9.34696153, 5.08980544, 
                       -0.26983873, -1.47667864, 1.96580794, 
                       6.87009791, -2.07784135, -0.7726816, 
                       -2.74954984])
np.testing.assert_allclose(y, y_expected)
print ('****** Tests passed! ******')

[-0.45481164  0.29282121 -0.04605458 -3.78610463 -1.19921111  0.71335536]
X_no_constant:
[[-0.92232935  0.27352359 -0.86339625  1.43766044 -1.71379871]
 [ 0.179322   -0.89138595  2.13005603  0.51898975 -0.41875106]
 [ 0.34010119 -1.07736609 -1.02314142 -1.02518535  0.40972072]
 [ 1.18883814  1.01044759  0.3108216  -1.17868611 -0.49526331]
 [-1.50248369 -0.196458    0.34752922 -0.79200465 -0.31534705]
 [ 1.73245191 -1.42793626 -0.94376587  0.86823495 -0.95946769]
 [-1.07074604 -0.06555247 -2.17689578  1.58538804  1.81492637]
 [-0.73706088  0.77546031  0.42653908 -0.51853723 -0.53045538]
 [ 1.09620536 -0.69557321  0.03080082  0.25219596 -0.35304303]
 [-0.93971165  0.04448078  0.04273069  0.4961477  -1.7673568 ]]
(10, 5)
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-0.92232935  0.179322    0.34010119  1.18883814 -1.50248369  1.73245191
  -1.07074604 -0.73706088  1.09620536 -0.93971165]
 [ 0.27352359 -0.89138595 -1.07736609  1.01044759 -0.196458   -1.42793626
  

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(shapes (1, 10), (10,) mismatch)
 x: array([[-2.135228, -1.190096,  3.680435,  5.510778,  4.69995 , -2.585873,
        -6.897521,  3.855371, -0.521776,  1.392771]])
 y: array([-0.415184, -9.346962,  5.089805, -0.269839, -1.476679,  1.965808,
        6.870098, -2.077841, -0.772682, -2.74955 ])

In [88]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

print (betas)

[-0.45481164  0.29282121 -0.04605458 -3.78610463 -1.19921111  0.71335536]


In [89]:
betas.shape

(6,)

In [90]:
X_no_constant = np.random.randn(n_data, n_dim)
print ('X_no_constant:')
print (X_no_constant)
print 

print (X_no_constant.shape)



X_no_constant:
[[-0.92232935  0.27352359 -0.86339625  1.43766044 -1.71379871]
 [ 0.179322   -0.89138595  2.13005603  0.51898975 -0.41875106]
 [ 0.34010119 -1.07736609 -1.02314142 -1.02518535  0.40972072]
 [ 1.18883814  1.01044759  0.3108216  -1.17868611 -0.49526331]
 [-1.50248369 -0.196458    0.34752922 -0.79200465 -0.31534705]
 [ 1.73245191 -1.42793626 -0.94376587  0.86823495 -0.95946769]
 [-1.07074604 -0.06555247 -2.17689578  1.58538804  1.81492637]
 [-0.73706088  0.77546031  0.42653908 -0.51853723 -0.53045538]
 [ 1.09620536 -0.69557321  0.03080082  0.25219596 -0.35304303]
 [-0.93971165  0.04448078  0.04273069  0.4961477  -1.7673568 ]]
(10, 5)


In [91]:
# INSERT YOUR CODE HERE!

onesv=np.ones((10, 1))
print (onesv)

#[[ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]]



[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [93]:
onesv.shape

(10, 1)

In [94]:
baseX=np.hstack([X_no_constant, onesv])



In [95]:
baseX
baseX.shape

(10, 6)

In [ ]:
#Transpose matrix
baseX.T
print (baseX.T)

baseX.T.shape
betas.shape


In [96]:


#matrix multiplication
# you can perform matrix multiplication with np.dot()
y = np.dot(baseX,betas)

# Tests:


In [97]:
print (y)

[-2.13522804 -1.19009649  3.68043545  5.51077786  4.6999502  -2.58587328
 -6.89752086  3.85537055 -0.52177587  1.39277092]


In [98]:
y.shape

(10,)

In [ ]:
y_expected = np.array([-0.41518357, -9.34696153, 5.08980544, 
                       -0.26983873, -1.47667864, 1.96580794, 
                       6.87009791, -2.07784135, -0.7726816, 
                       -2.74954984])


In [ ]:
np.testing.assert_allclose(y, y_expected)
print ('****** Tests passed! ******')

In [30]:
baseX.T.shape


(6, 10)

In [31]:
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

In [52]:
betas.reshape(1,6)

array([[-0.45481164,  0.29282121, -0.04605458, -3.78610463, -1.19921111,
         0.71335536]])

In [48]:
baseX.T.shape



(6, 10)

In [ ]:
#a-columns = b-rows

In [28]:
betas.shape

(6,)

## Pandas
Pandas is a python package which adds some useful data analysis features to numpy arrays.  Most importantly, it contains a `DataFrame` data type like the r `dataframe`: a set of named columns organized into something like a 2d array.  Pandas is great.

### Resources:
* [10 Minutes to Pandas](http://pandas.pydata.org/pandas-docs/dev/10min.html)
* [Pandas Data Structures Tutorial](http://pandas.pydata.org/pandas-docs/stable/dsintro.html)
* [Merge, Join, Concatenate Tutorial](http://pandas.pydata.org/pandas-docs/dev/merging.html)
* [Another Numpy/Pandas Tutorial](https://www.kaggle.com/c/titanic/details/getting-started-with-python-ii)

In [5]:
# like with numpy, you don't have to rename pandas to pd, but it's customary to do so
import numpy as np
import pandas as pd

b = np.array([[6, 7], [3, 1], [4, 0]])
df = pd.DataFrame(data=b,  columns=['Weight', 'Height'])
print ('b:')
print (b)
print 
print ('DataFame version of b:')
print (df)
print

b:
[[6 7]
 [3 1]
 [4 0]]
DataFame version of b:
   Weight  Height
0       6       7
1       3       1
2       4       0


<function print>

In [6]:
# Pandas can save and load CSV files.  
# Python can do this too, but with Pandas, you get a DataFrame 
# at the end which understands things like column headings
baseball = pd.read_csv('data/baseball.dat.txt')

# A Dataframe's .head() method shows its first 5 rows
baseball.head()

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks   SO  \
0    3300  0.272  0.302    69   153       21        4  31  104     22   80   
1    2600  0.269  0.335    58   111       17        2  18   66     39   69   
2    2500  0.249  0.337    54   115       15        1  17   73     63  116   
3    2475  0.260  0.292    59   128       22        7  12   50     23   64   
4    2313  0.273  0.346    87   169       28        5   8   58     70   53   

   SB  Errs  free agency eligibility  free agent in 1991/2  \
0   4     3                        1                     0   
1   0     3                        1                     1   
2   6     5                        1                     0   
3  21    21                        0                     0   
4   3     8                        0                     0   

   arbitration eligibility  arbitration in 1991/2            Name  
0                        0                      0    Andre Dawson  
1                        0                      0   Steve Buchele  
2                        0                      0     Kal Daniels  
3                        1                      0  Shawon Dunston  
4                        1                      0      Mark Grace

In [10]:
# you can see all the column names
print ('baseball.keys():')
baseball.keys()
print

print ('baseball.Salary:')
#print baseball.Salary
print 
#print ("baseball['Salary']:")
print (baseball['Salary'])

baseball.keys():
baseball.Salary:
0      3300
1      2600
2      2500
3      2475
4      2313
5      2175
6       600
7       460
8       240
9       200
10      177
11      140
12      117
13      115
14     2600
15     1907
16     1190
17      990
18      925
19      365
20      302
21      300
22      129
23      111
24     6100
25     4125
26     3213
27     2319
28     2000
29     1600
       ... 
307     205
308     185
309     115
310    3750
311    2188
312    2167
313    2167
314    2050
315    1445
316     875
317     560
318     360
319     162
320     133
321     109
322    4300
323    3850
324    2387
325     950
326     675
327     600
328     287
329     230
330     215
331     183
332     170
333     160
334     142
335     140
336     109
Name: Salary, dtype: int64


In [11]:
baseball.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 336
Data columns (total 18 columns):
Salary                     337 non-null int64
AVG                        337 non-null float64
OBP                        337 non-null float64
Runs                       337 non-null int64
Hits                       337 non-null int64
Doubles                    337 non-null int64
Triples                    337 non-null int64
HR                         337 non-null int64
RBI                        337 non-null int64
Walks                      337 non-null int64
SO                         337 non-null int64
SB                         337 non-null int64
Errs                       337 non-null int64
free agency eligibility    337 non-null int64
free agent in 1991/2       337 non-null int64
arbitration eligibility    337 non-null int64
arbitration in 1991/2      337 non-null int64
Name                       337 non-null object
dtypes: float64(2), int64(15), object(1)
memory usage: 50.0+ K

In [12]:
baseball.describe()

Salary         AVG         OBP        Runs        Hits  \
count   337.000000  337.000000  337.000000  337.000000  337.000000   
mean   1248.528190    0.257825    0.323973   46.697329   92.833828   
std    1240.013309    0.039546    0.047132   29.020166   51.896322   
min     109.000000    0.063000    0.063000    0.000000    1.000000   
25%     230.000000    0.238000    0.297000   22.000000   51.000000   
50%     740.000000    0.260000    0.323000   41.000000   91.000000   
75%    2150.000000    0.281000    0.354000   69.000000  136.000000   
max    6100.000000    0.457000    0.486000  133.000000  216.000000   

          Doubles     Triples          HR         RBI       Walks          SO  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean    16.673591    2.338279    9.097923   44.020772   35.017804   56.706231   
std     10.452001    2.543336    9.289934   29.559406   24.842474   33.828784   
min      0.000000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%      9.000000    0.000000    2.000000   21.000000   15.000000   31.000000   
50%     15.000000    2.000000    6.000000   39.000000   30.000000   49.000000   
75%     23.000000    3.000000   15.000000   66.000000   49.000000   78.000000   
max     49.000000   15.000000   44.000000  133.000000  138.000000  175.000000   

               SB        Errs  free agency eligibility  free agent in 1991/2  \
count  337.000000  337.000000               337.000000            337.000000   
mean     8.246291    6.771513                 0.397626              0.115727   
std     11.664782    5.927490                 0.490135              0.320373   
min      0.000000    0.000000                 0.000000              0.000000   
25%      1.000000    3.000000                 0.000000              0.000000   
50%      4.000000    5.000000                 0.000000              0.000000   
75%     11.000000    9.000000                 1.000000              0.000000   
max     76.000000   31.000000                 1.000000              1.000000   

       arbitration eligibility  arbitration in 1991/2  
count               337.000000             337.000000  
mean                  0.192878               0.029674  
std                   0.395145               0.169938  
min                   0.000000               0.000000  
25%                   0.000000               0.000000  
50%                   0.000000               0.000000  
75%                   0.000000               0.000000  
max                   1.000000               1.000000

In [13]:
baseball

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks   SO  \
0      3300  0.272  0.302    69   153       21        4  31  104     22   80   
1      2600  0.269  0.335    58   111       17        2  18   66     39   69   
2      2500  0.249  0.337    54   115       15        1  17   73     63  116   
3      2475  0.260  0.292    59   128       22        7  12   50     23   64   
4      2313  0.273  0.346    87   169       28        5   8   58     70   53   
5      2175  0.291  0.379   104   170       32        2  26  100     87   89   
6       600  0.258  0.370    34    86       14        1  14   38     15   45   
7       460  0.228  0.279    16    38        7        2   3   21     11   32   
8       240  0.250  0.327    40    61       11        0   1   18     24   26   
9       200  0.203  0.240    39    64       10        1  10   33     14   96   
10      177  0.262  0.283     7    38        5        0   0   10      5   18   
11      140  0.222  0.307    21    45        9        0   6   22     19   56   
12      117  0.227  0.280     4     5        2        0   1    3      2    1   
13      115  0.261  0.370     1     6        0        0   0    2      4    3   
14     2600  0.300  0.368    69   141       22        3  19   75     53   64   
15     1907  0.225  0.292    60   130       22        1  13   73     50  100   
16     1190  0.255  0.321    39   108       22        8   3   26     42   61   
17      990  0.290  0.349    59   141       30        2  16   64     42  102   
18      925  0.246  0.323    22    81       14        0   6   26     22   26   
19      365  0.208  0.265    12    35       11        1   0   15     14   30   
20      302  0.238  0.347    83   134       15        4  10   51     95  151   
21      300  0.267  0.310    73   149       23        9   6   39     34   89   
22      129  0.353  0.435    16    48       12        2   2   18     20   22   
23      111  0.213  0.222     4    13        4        1   1    8      1   18   
24     6100  0.302  0.391   102   174       44        6  18  100     90   67   
25     4125  0.260  0.321    69   150       23        1  19   96     55   74   
26     3213  0.255  0.347    45    71        7        5   1   17     39   47   
27     2319  0.259  0.349   108   146       34        4  38  117     78  120   
28     2000  0.223  0.307    43    84       10        4  10   40     36   56   
29     1600  0.225  0.310    44    96        9        3   0   31     50   69   
..      ...    ...    ...   ...   ...      ...      ...  ..  ...    ...  ...   
307     205  0.249  0.336    33    46        8        0   3   21     23   42   
308     185  0.238  0.289    21    56        5        1   0   21     14   37   
309     115  0.235  0.268     9    16        5        0   2    4      3   11   
310    3750  0.256  0.338    52    95       13        1  27   69     43   57   
311    2188  0.248  0.300    58   139       29        3  17   88     44   61   
312    2167  0.254  0.332    95   160       34        6   3   57     72   63   
313    2167  0.194  0.286    38    63        8        1   8   32     34   49   
314    2050  0.327  0.399    76   179       42        1  22  100     71   82   
315    1445  0.244  0.337    64    99       14        4  27   77     53  117   
316     875  0.305  0.347    35    54        6        2   6   23     10   27   
317     560  0.307  0.405    98   167       35        1  14   52     84   72   
318     360  0.230  0.302    42    98       16        4   1   41     45   37   
319     162  0.247  0.286    16    44       13        0   2   22      9   38   
320     133  0.205  0.272    11    23        2        0   4    9     11   24   
321     109  0.216  0.285    38    87       12        0  19   51     35  117   
322    4300  0.266  0.359   115   152       32        1  44  122     78  152   
323    3850  0.322  0.389   115   203       49        3  26   88     68   72   
324    2387  0.341  0.408   108   201       27        3  15   78     65   78   
325  

In [15]:
# You can perform queries on your data frame.  
# This statement gives you a True/False vector telling you 
# whether the player in each row has a salary over $1 Million
millionaire_indices = baseball['Salary'] > 1000
print (millionaire_indices)

0       True
1       True
2       True
3       True
4       True
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14      True
15      True
16      True
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
307    False
308    False
309    False
310     True
311     True
312     True
313     True
314     True
315     True
316    False
317    False
318    False
319    False
320    False
321    False
322     True
323     True
324     True
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
Name: Salary, dtype: bool


In [17]:
# you can use the query indices to look at a subset of your original dataframe
print ('baseball.shape:', baseball.shape)
print ("baseball[millionaire_indices].shape:", baseball[millionaire_indices].shape)

baseball.shape: (337, 18)
baseball[millionaire_indices].shape: (139, 18)


In [18]:
# you can look at a subset of rows and columns at the same time
print ("baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]:")
baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]

baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]:


Salary    AVG  Runs              Name
0      3300  0.272    69      Andre Dawson
1      2600  0.269    58     Steve Buchele
2      2500  0.249    54       Kal Daniels
3      2475  0.260    59    Shawon Dunston
4      2313  0.273    87        Mark Grace
5      2175  0.291   104     Ryne Sandberg
14     2600  0.300    69     Ivan Calderon
15     1907  0.225    60       Tim Wallach
16     1190  0.255    39        Spike Owen
24     6100  0.302   102     Bobby Bonilla
25     4125  0.260    69      Eddie Murray
26     3213  0.255    45     Vince Coleman
27     2319  0.259   108    Howard Johnson
28     2000  0.223    43        Kevin Bass
29     1600  0.225    44    Dick Schofield
30     1394  0.258    58      Dave Magadan
38     2567  0.196    36    Darren Daulton
39     2500  0.252    66       Dale Murphy
40     2350  0.294    84         John Kruk
41     2317  0.297    48     Lenny Dykstra
42     2000  0.258    46    Mariano Duncan
51     5150  0.292    95       Barry Bonds
52     4450  0.265    87    Andy Van Slyke
53     2000  0.265    53         Jose Lind
54     1850  0.289    25   Mike LaValliere
55     1192  0.295    19       Don Slaught
65     2425  0.272    41    Pedro Guerrero
66     2367  0.219    34  Andres Galarraga
67     2050  0.240    37      Jose Guillen
68     2000  0.285    96       Ozzie Smith
..      ...    ...   ...               ...
257    1350  0.241    42      Carlton Fisk
268    4200  0.301    79      Wally Joyner
269    3417  0.259    65  Kevin McReynolds
270    3100  0.255    77      George Brett
271    1650  0.301    47    Jim Eisenreich
272    1150  0.272    59    Gregg Jeffries
284    3100  0.284    72        Kent Hrbek
285    2992  0.319    92     Kirby Puckett
286    2800  0.277    84       Chili Davis
287    2500  0.311    54      Brian Harper
288    1933  0.265    52        Greg Gagne
289    1200  0.279    36   Mike Pagliarulo
290    1075  0.310    79        Shane Mack
296    5000  0.307   110      Ruben Sierra
297    3250  0.268   105  Rickey Henderson
298    2825  0.201    62      Mark McGwire
299    2600  0.276    86    Dave Henderson
300    2050  0.274    50   Terry Steinbach
301    1583  0.295    76     Harold Baines
302    1150  0.063     0   Carney Lansford
303    1100  0.238    38     Willie Wilson
310    3750  0.256    52    Kevin Mitchell
311    2188  0.248    58      Pete O'Brien
312    2167  0.254    95   Harold Reynolds
313    2167  0.194    38        Dave Valle
314    2050  0.327    76       Ken Griffey
315    1445  0.244    64        Jay Buhner
322    4300  0.266   115      Jose Canseco
323    3850  0.322   115   Rafael Palmeiro
324    2387  0.341   108      Julio Franco

[139 rows x 4 columns]

## Pandas Joins
The real magic with a Pandas DataFrame comes from the merge method which can match up the rows and columns from two DataFrames and combine their data.  Let's load another file which has shoesize for just a few players

In [19]:
# load shoe size data
shoe_size_df = pd.read_csv('data/baseball2.dat.txt')
shoe_size_df

Shoe Size          Name
0         11  Andre Dawson
1         13    Mark Grace
2         12    Sammy Sosa

In [20]:
merged = pd.merge(baseball, shoe_size_df, on=['Name'])
merged

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks  SO  SB  \
0    3300  0.272  0.302    69   153       21        4  31  104     22  80   4   
1    2313  0.273  0.346    87   169       28        5   8   58     70  53   3   
2     200  0.203  0.240    39    64       10        1  10   33     14  96  13   

   Errs  free agency eligibility  free agent in 1991/2  \
0     3                        1                     0   
1     8                        0                     0   
2     6                        0                     0   

   arbitration eligibility  arbitration in 1991/2          Name  Shoe Size  
0                        0                      0  Andre Dawson         11  
1                        1                      0    Mark Grace         13  
2                        0                      0    Sammy Sosa         12

In [ ]:
merged_outer = pd.merge(baseball, shoe_sizes, on=['Name'], how='outer')
merged_outer.head()

### <span style="color:red">Pandas Exercise</span>
1. Partner up with someone next to you.  Then, on one of your computers:
  1. Prepend a column of ones to the dataframe `X_df` below.  Name the new column 'const'.
  1. Again, matrix multiply `X_df` by the `betas` vector and assign the result to an new variable: `y_new`
  1. You'll know you've got it when the cell prints '\*\*\*\*\*\* Tests passed! \*\*\*\*\*\*' at the bottom.

  **Hint**: This stackoverflow post may be useful: http://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns

In [59]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

X_df = pd.DataFrame(data=np.random.randn(n_data, n_dim))

# INSERT YOUR CODE HERE!
const=np.ones((5, 1))
baseX=np.hstack([X_df, const])

y_new=np.dot(baseX,betas)

# Tests:
assert 'const' in X_df.keys(), 'The new column must be called "const"'
assert np.all(X_df.shape == (n_data, n_dim+1))
assert len(y_new == n_data)
print ('****** Tests passed! ******')


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [82]:
const=np.ones((1, 5))

In [64]:
print (const)

[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [65]:
print (X_df)

          0         1         2         3         4
0 -0.922329  0.273524 -0.863396  1.437660 -1.713799
1  0.179322 -0.891386  2.130056  0.518990 -0.418751
2  0.340101 -1.077366 -1.023141 -1.025185  0.409721
3  1.188838  1.010448  0.310822 -1.178686 -0.495263
4 -1.502484 -0.196458  0.347529 -0.792005 -0.315347
5  1.732452 -1.427936 -0.943766  0.868235 -0.959468
6 -1.070746 -0.065552 -2.176896  1.585388  1.814926
7 -0.737061  0.775460  0.426539 -0.518537 -0.530455
8  1.096205 -0.695573  0.030801  0.252196 -0.353043
9 -0.939712  0.044481  0.042731  0.496148 -1.767357


In [77]:
X_df.T.shape


(5, 10)

In [86]:
const.shape

(1, 5)

In [87]:
baseX=np.hstack([X_df.T, const])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [84]:
y_new=np.dot(baseX,betas)

ValueError: shapes (11,5) and (6,) not aligned: 5 (dim 1) != 6 (dim 0)

In [ ]:
print (baseX)

In [75]:
X_no_constant.shape


(10, 5)

In [74]:
onesv.shape

(10, 1)

In [101]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

print (betas)

X_no_constant = np.random.randn(n_data, n_dim)
print ('X_no_constant:')
print (X_no_constant)
print 

print (X_no_constant.shape)

# INSERT YOUR CODE HERE!

onesv=np.ones((10, 1))
print (onesv)

#[[ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]
# [ 1.  1.  1.  1.]]

baseX=np.hstack([X_no_constant, onesv])

#Transpose matrix
baseX.T
print (baseX.T)

baseX.T.shape
betas.shape


#matrix multiplication
# you can perform matrix multiplication with np.dot()
y = np.dot(baseX,betas)

print (y)

# Tests:
#y_expected = np.array([-0.41518357, -9.34696153, 5.08980544, 
                      # -0.26983873, -1.47667864, 1.96580794, 
                      # 6.87009791, -2.07784135, -0.7726816, 
                      # -2.74954984])
#np.testing.assert_allclose(y, y_expected)
#print ('****** Tests passed! ******')

[-0.45481164  0.29282121 -0.04605458 -3.78610463 -1.19921111  0.71335536]
X_no_constant:
[[-0.92232935  0.27352359 -0.86339625  1.43766044 -1.71379871]
 [ 0.179322   -0.89138595  2.13005603  0.51898975 -0.41875106]
 [ 0.34010119 -1.07736609 -1.02314142 -1.02518535  0.40972072]
 [ 1.18883814  1.01044759  0.3108216  -1.17868611 -0.49526331]
 [-1.50248369 -0.196458    0.34752922 -0.79200465 -0.31534705]
 [ 1.73245191 -1.42793626 -0.94376587  0.86823495 -0.95946769]
 [-1.07074604 -0.06555247 -2.17689578  1.58538804  1.81492637]
 [-0.73706088  0.77546031  0.42653908 -0.51853723 -0.53045538]
 [ 1.09620536 -0.69557321  0.03080082  0.25219596 -0.35304303]
 [-0.93971165  0.04448078  0.04273069  0.4961477  -1.7673568 ]]
(10, 5)
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-0.92232935  0.179322    0.34010119  1.18883814 -1.50248369  1.73245191
  -1.07074604 -0.73706088  1.09620536 -0.93971165]
 [ 0.27352359 -0.89138595 -1.07736609  1.01044759 -0.196458   -1.42793626
  